### ISSUE TITLE
Empty class constructors are not being correctly parsed

### ISSUE THREAD

**Issue by joaocandre** [20Tauri/DoxyDoxygen#155] opened 2021-06-08 20:51 UTC
I've noticed a small bug when attempting to auto-generate docblocks for empty class constructors e.g. `MyClass()`, no comments are added and on the status bar `[doxy] cannot parse definition... command aborted` appears.

Also, not really a bug but rather an (apparent) feature regression and mildly inconvenient, is that when auto-parsing class constructor definitions, no default description is provided. I specifically remember that previous versions placed a preset generic description similar to `Constructs a new instance` with the `@brief` tag.

**Comment by 20Tauri** [comment] 2021-06-09 06:20
Thanks for reporting,

I cannot reproduce (c++, default syntax, _DoxyDoxygen Evolution_ lastest). The result is:
```c
class MyClass
{
    /**
     * @brief      Constructs a new instance.
     */
    MyClass()
    {
    }
};
```

Can you please add:
- an example
- the language (including sublime text syntax if it's not the default one)
- the sublime text version 
- the doxydoxygen version

**Comment by joaocandre** [comment] 2021-06-09 15:26
I'm attatching a short screencast of the issue I described.

Syntax: C++
SublimeText 3 (Build 4107)
DoxyDoxygen 0.79.0
![issue](https://user-images.githubusercontent.com/1812344/121383477-646e3980-c93f-11eb-8eff-ec1ad1cef85a.gif)

**Comment by 20Tauri** [comment] 2021-06-09 21:13
Thank reproduced
The C++ syntax has changed in 4107 and DoxyDoxygen no longer detects "MyClass ();" as a class name.
This will be fixed in the next DoxyDoxygen version

**Comment by 20Tauri** [comment] 2021-06-15 19:27
0.79.3 is now released on the evolution channel.
his release fixes this issue and a child issue.

**Closed as completed** 2021-08-16 17:28 UTC
