### ISSUE TITLE
Insert comment on <Enter> places curser on the wrong side

### ISSUE THREAD

**Issue by LDAP** [20Tauri/DoxyDoxygen#161] opened 2021-12-13 14:29 UTC
I updated ST today to 4124. DoxyDoxygen (Evolution) correctly inserts a new comment, but places the cursor on the wrong side:

In this situation: (`|` is the cursor)
```
// comment|
```

press enter

```
// comment
|// 
```
then this is the result.

Expected is this:
```
// comment
// |
```

**Comment by 20Tauri** [comment] 2021-12-14 19:11
Thank you for reporting,

This problem cannot be reproduced.
I assume you have changed the doxydoxygen parameter `continuation_on_singleline_comment` to `true`.
On a fresh install and only this parameter changed, it works fine (tested in php, javascript, c++).

Adding `mini_auto_complete`: `true` produce the referenced problem but not this one.

**Comment by LDAP** [comment] 2021-12-14 19:16
Hi! Sorry to report back that I used a empty DoxyDoxygen configuration. 
`continuation_on_singleline_comment` remained at the default value.

**Comment by LDAP** [comment] 2021-12-14 19:28
I retested it just now. 

That behavior happens only in exactly one of my C++ files. And it gets even better: If I copy the contents of the file into a new file the new file behaves perfectly normally. I am confused.

**Comment by rchl** [comment] 2021-12-15 09:41
Does it still reproduce if you close and re-open that file?

**Comment by LDAP** [comment] 2021-12-15 10:35
Yes it does! If i copy that file new new file shows the same behavior. Maybe its caused by the line-endings?

@20Tauri I can send you that file by mail if you want

**Comment by 20Tauri** [comment] 2021-12-15 17:56
This is really strange and probably a problem directly in SublimeText
The problematic C++ file would help (don't forget to tell me where to place the cursor).
If there is a workaround, a new version of the plugin will be delivered

**Comment by 20Tauri** [comment] 2021-12-15 18:36
The bug is caused when both:
- there's a tab before the comment
- SublimeText is configured to replace tab by spaces

In this case, the new cursor position is not the length of this inserted text (has it has been altered by SublimeText)

The occurence should be rare, but will be fixed in the next release.
Not a bug in SublimeText, bug in the plugin

**Comment by 20Tauri** [comment] 2021-12-20 22:30
Fixed in 0.79.5.
Just released on evolution branch

**Closed as completed by 20Tauri** 2021-12-20 22:30 UTC
