### ISSUE TITLE
Better handling of row styles without asterisk

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#20] opened 2015-09-23 18:40 UTC
## 1. Improper manual tag indentation

Given this style:

```
[
  "/**",
  "  "  // 1 space
],
```

You get this behavior:
![doxygen7](https://cloud.githubusercontent.com/assets/662874/10054382/95fa198c-61e5-11e5-931d-292dc79faaf2.gif)
- automatically generated tags have an additional space prepended.
- manually entered tags do **not** have an additional space prepended, and therefore are not indented correctly.
- running the 'comment nearest entity command' (`Super`+`Alt`+`Q` on mac) will correctly update indentation, but that shouldn't be necessary...
  - side note: should text following the `@todo` tag respect the columns? As you can see above, it currently does not.

Compare that to the default column style of:

```
[
  "/**",
  "  *"  // default
],
```

![doxygen8](https://cloud.githubusercontent.com/assets/662874/10054532/5e5b31c2-61e6-11e5-912f-61e417ab5d71.gif)
- manually entered tags **do** have an additional space prepended
## 2. Empty row style shifts tags up to first row

Given this style:

```
[
  "/**",
  ""  // 0 spaces
],
```

You get this behavior:
![doxygen9](https://cloud.githubusercontent.com/assets/662874/10054638/126c4390-61e7-11e5-83b1-e8eab974bbcd.gif)
## 3. No way to have tags completely left-aligned

Even if item 2. in this issue was addressed, It should be noted that it is also currently impossible to achieve a block that looks like:

```
|/**
|@brief      stuff
|@param      bar   stuff
| */
```

_(`|` character added to denote left-most margin)_

It would be nice to disable the default insertion of an additional space before each @tag. this might also provide an easy workaround to item 1. since there would be no indentation difference anymore between automatic and manually entered tags.

**Comment by 20Tauri** [comment] 2015-09-24 22:15
### Point 1

In first versions, <kbd>Return</kbd>, only add " *" (without space)
When I made the change, I forget this special case.
This case, is now under test to prevent future regression.

### Point 2

Cannot reproduce with 0.19.2. In 0.19.1, I improve the comment style detection, may explain.
Please let me know if it also fixed on your side. Thanks

### Point 3

Space insertion is "on return", not after a @tag...
But you are right, there is currently no way to align documentation block to comment style...
May be an enhancement

**Comment by 20Tauri** [comment] 2015-09-25 17:46
Point 1 is fixed in 0.19.2.
Point 2 may be improved. I have reproduced it now by removing a blank line in my "block_layout" section

``` javascript
        "Doxygen": [
            "", //// <= you probably haven't this
```

Point 3 is now possible in 0.21.0

**Comment by 20Tauri** [comment] 2015-10-13 19:08
Point 2 is now improved... As line have different length a blank line is forced

```
[
  "/**",
  "  "  // 1 space
],
```

**Comment by 20Tauri** [comment] 2015-10-15 22:45
All points seem to be ok now.
Thanks again for your outstanding reporting (really appreciate)

**Closed as completed by 20Tauri** 2015-10-15 22:45 UTC
Labels: bug, enhancement
