### ISSUE TITLE
How to disable alignment?

### ISSUE THREAD

**Issue by ifeltsweet** [20Tauri/DoxyDoxygen#30] opened 2015-12-26 11:02 UTC
Instead of

``` php
/**
 * Loads stuff.
 *
 * @param \Illuminate\View\View $view
 * @param int                   $homeTeamId
 * @param int                   $awayTeamId
 */
```

I want

``` php
/**
 * Loads stuff.
 *
 * @param \Illuminate\View\View $view
 * @param int $sellerId
 * @param int $buyerId
 */
```

**Comment by 20Tauri** [comment] 2015-12-27 20:12
Not possible with versions prior to 0.28.2.
In 0.28.2, set `preferred_tabs_sizes` to [0] to remove all alignment

**Comment by 20Tauri** [comment] 2016-01-03 12:50
Released in both "stable" and "evoltution" branches

**Closed as completed by 20Tauri** 2016-01-03 12:50 UTC
Labels: enhancement

**Comment by ifeltsweet** [comment] 2016-01-04 17:41
Using version 0.28.4 this worked only on the first time when creating a doc block. However, when reformatting the doc block with comment update command (regardless if preserving style or including style) the strings will be aligned.

To fix this I needed to add the following line in addition to what you said:

```
"min_spaces_between_columns": [-100]
```

-100 seems to be a large enough value.

**Comment by 20Tauri** [comment] 2016-01-04 18:30
Thanks for the information. I've restated it (with 0.29.2 but there's no change on this point) and I cannot reproduce the problem. This is probably not context dependant, but if you have an incorrect example, I will fix it.

**Comment by ifeltsweet** [comment] 2016-01-04 18:40
With only `preferred_tabs_sizes` to `[0]` in user setting, try this:

``` php
<?php

namespace Acme\Core\Vote;

use Acme\Core\Vote\PollChoice;

class Vote
{
    /**
     * @var string
     */
    protected $pollId;

    /**
     * @var int
     */
    protected $userId;

    /**
     * @var string
     */
    protected $tracker;

    /**
     * @var \Acme\Core\Vote\PollChoice
     */
    protected $choice;

    /**
     * Constructor.
     *
     * @param int $pollId
     * @param PollChoice $choice
     * @param int $tracker
     * @param int $userId
     */
    public function __construct($pollId, PollChoice $choice, $tracker, $userId)
    {
        $this->pollId = $pollId;
        $this->choice = $choice;
        $this->tracker = $tracker;
        $this->userId = $userId;
    }
}
```

Place cursor to constructor's doc block and run the update comment command. You will see how params names move 1 space to the right. Now completely remove the comment block and create a new one, fill in the placeholders and try updating comment again. Did you see it try to align things once more?

**Comment by 20Tauri** [comment] 2016-01-04 18:47
It's probably because `min_spaces_between_columns` is set to the default value

``` js
    "min_spaces_between_columns": [ 1, 2 ],
```

Try:

``` js
    "min_spaces_between_columns": [ 1 ],
```

**Comment by ifeltsweet** [comment] 2016-01-04 18:55
Sure, I've tried it with `"min_spaces_between_columns": [ 1 ],` and it works for the discussed case but it doesn't help in all cases.

If you take my previous example as it is except the following line changed from:

``` php
* @param PollChoice $choice
```

to:

``` php
* @param \Acme\Core\Vote\PollChoice $choice
```

and try updating comment you will see that alignment is forced once again. It seems that only a large enough negative value for `min_spaces_between_columns` fixes it.

**Comment by 20Tauri** [comment] 2016-01-04 22:28
Your example has reveal severals issues (describe in 0.29.2 release notes)

I have added your example in my test suite (a good example for the FQN functionnaly)
Now work (regardless `min_spaces_between_columns` values), and FQN are correctly guessed.

``` php
<?php

namespace Acme\Core\Vote;

use Acme\Core\Vote\PollChoice;

class Vote
{
    /**
     * { function_description }
     *
     * @param <type> $pollId (description)
     * @param Acme\Core\Vote\PollChoice $choice (description)
     * @param <type> $tracker (description)
     * @param <type> $userId (description)
     */
    public function __construct($pollId, PollChoice $choice, $tracker, $userId)
    {
        $this->pollId = $pollId;
        $this->choice = $choice;
        $this->tracker = $tracker;
        $this->userId = $userId;
    }
}
```
